language: csharp

mono: none

dotnet: 3.1

install: dotnet restore

script: 
 - dotnet build
 - dotnet test DvBCrud.EFCore.Tests/DvBCrud.EFCore.Tests.csproj
 - dotnet test DvBCrud.EFCore.API.Tests/DvBCrud.EFCore.API.Tests.csproj
