language: csharp

mono: none

dotnet: 3.1

install:
 - dotnet restore

jobs:
  include:
  - stage: build
    script: dotnet build
  - stage: test
    script: dotnet test DvBCrud.EFCore.Tests/DvBCrud.EFCore.Tests.csproj
  -
    script: dotnet test DvBCrud.EFCore.API.Tests/DvBCrud.EFCore.API.Tests.csproj
  - stage: test coverage
    script: bash <(curl -s https://codecov.io/bash)

stages:
  - build
  - test
  - test coverage
