language: csharp

mono: none

dotnet: 3.1

jobs:
  include:
  - stage: build
    install: dotnet restore
    script: dotnet build
    workspaces:
      create:
        name: ws
  - stage: test
    script: dotnet test DvBCrud.EFCore.Tests/DvBCrud.EFCore.Tests.csproj
    workspaces:
      use: ws
  - 
    script: dotnet test DvBCrud.EFCore.API.Tests/DvBCrud.EFCore.API.Tests.csproj
    workspaces:
      use: ws
