name: NuGet release
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:  
  release:
    name: Release
    strategy:
      matrix:
        project:
          - DvBCrud.EFCore
          - DvBCrud.EFCore.Services
          - DvBCrud.EFCore.API
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Pack
        run: dotnet pack -c Release -p:PackageVersion="${{ github.event.release.tag_name }}" ${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Publish
        run: dotnet nuget push ${{ matrix.project }}/bin/Release/${{ matrix.project }}.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
